config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :categories
  devise_for :users
  root to: 'dashboard#index', as: :dashboard
  resources :annotations

  put '/mark_review_as_done/:id' => 'reviews#mark_as_done', as: 'mark_review_as_done'
  get '/mark_all_reviews_as_done' => 'reviews#mark_all_reviews_as_done', as: 'mark_all_reviews_as_done'
  get '/randomize_non_reviewed' => 'reviews#randomize_non_reviewed', as: 'randomize_non_reviewed'

  get '/testing_email' => 'dashboard#testing_email', as: 'testing_email'
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  def index
    @reviews = Review.today_reviews(current_user.id)
  end
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

module DashboardHelper
end

app/views/dashboard/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Review Date</th>
      <th>Category</th>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= link_to 'Mark All Done', mark_all_reviews_as_done_path,
      :method => :get, data: { confirm: "Are you sure??" },
      id: "mark_all_reviews_as_done" %>
    &nbsp; | &nbsp;
    <%= link_to 'OMG, this is too much for one day!!!', randomize_non_reviewed_path,
      :method => :get, data: { confirm: "Are you sure??" },
      id: "randomize_non_reviewed" %>

    <% @reviews.each do |review| %>
      <tr>
        <td>
          <%= review.id %>
          <input type="hidden" id="review_<%= review.id %>" value="<%= review.id %>">
        </td>
        <td><%= review.date.strftime("%d/%m/%Y") %></td>
        <td><%= review.reviewable.category.name %></td>
        <td><%= review.reviewable.title %></td>
        <td><%= review.reviewable.content %></td>
        <td>
          <%= link_to 'Done', mark_review_as_done_path(review),
            :method => :put, data: { confirm: "Are you sure??" },
            id: "mark_review_as_done_#{review.id}" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br/>

<div>
  <%= link_to "Annotations", annotations_path %>
  <br/>
  <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <br/>
  <br/>
  <br/>
</div>

app/views/dashboard/testing_email.html.erb
TESTING!