config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :categories
  devise_for :users
  root to: 'dashboard#index', as: :dashboard
  resources :annotations

  put '/mark_review_as_done/:id' => 'reviews#mark_as_done', as: 'mark_review_as_done'
  get '/mark_all_reviews_as_done' => 'reviews#mark_all_reviews_as_done', as: 'mark_all_reviews_as_done'
  get '/randomize_non_reviewed' => 'reviews#randomize_non_reviewed', as: 'randomize_non_reviewed'

  get '/testing_email' => 'dashboard#testing_email', as: 'testing_email'
end

app/models/annotation.rb
# frozen_string_literal: true

class Annotation < ApplicationRecord
  include ReviewGenerator
  has_many :reviews, as: :reviewable, dependent: :destroy
  belongs_to :category
  belongs_to :user

  scope :by_user_id, ->(user_id) { where(user_id: user_id) }

  after_create :generate_next_review

  def next_review
    reviews.pending.first
  end
end

app/controllers/annotations_controller.rb
# frozen_string_literal: true

class AnnotationsController < ApplicationController
  before_action :set_annotation, only: %i[show edit update destroy]

  # GET /annotations
  # GET /annotations.json
  def index
    @annotations = Annotation.by_user_id(current_user.id)
  end

  # GET /annotations/1
  # GET /annotations/1.json
  def show; end

  # GET /annotations/new
  def new
    @annotation = Annotation.new
  end

  # GET /annotations/1/edit
  def edit; end

  # POST /annotations
  # POST /annotations.json
  def create
    @annotation = Annotation.new(annotation_params)
    @annotation.user = current_user

    respond_to do |format|
      if @annotation.save
        format.html { redirect_to @annotation, notice: 'Annotation was successfully created.' }
        format.json { render :show, status: :created, location: @annotation }
      else
        format.html { render :new }
        format.json { render json: @annotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /annotations/1
  # PATCH/PUT /annotations/1.json
  def update
    respond_to do |format|
      if @annotation.update(annotation_params)
        format.html { redirect_to @annotation, notice: 'Annotation was successfully updated.' }
        format.json { render :show, status: :ok, location: @annotation }
      else
        format.html { render :edit }
        format.json { render json: @annotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /annotations/1
  # DELETE /annotations/1.json
  def destroy
    @annotation.destroy
    respond_to do |format|
      format.html { redirect_to annotations_url, notice: 'Annotation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_annotation
    @annotation = Annotation.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def annotation_params
    params.require(:annotation).permit(:title, :content, :category_id)
  end
end

app/helpers/annotations_helper.rb
# frozen_string_literal: true

module AnnotationsHelper
end

app/views/annotations/_form.html.erb
<div class="row">
  <%= form_with(model: annotation, local: true, :html => {:class => 'col s12'}) do |form| %>
    <div class="row">
      <% if annotation.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(annotation.errors.count, "error") %> prohibited this annotation from being saved:</h2>

          <ul>
          <% annotation.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    </div>

    <div class="row">
      <div class="input-field col s12">
        <%= form.label :title %>
        <%= form.text_field :title, id: :annotation_title, class: 'active' %>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s12">
        <%= form.label :content %>
        <%= form.text_field :content, id: :annotation_content %>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s12">
        <%= form.collection_select(:category_id, Category.by_user_id(current_user), :id, :name, {}, {:id => "choose-category"}) %>
        <%= form.label :category %>
      </div>
    </div>

    <div class="actions">
      <%= form.button 'Save', type: :submit, class: 'waves-effect waves-light btn' %>
    </div>
  <% end %>
</div>

app/views/annotations/edit.html.erb
<h1>Editing Annotation</h1>

<%= render 'form', annotation: @annotation %>

<%= link_to 'Show', @annotation %> |
<%= link_to 'Back', annotations_path %>

app/views/annotations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Annotations</h1>

<%= link_to 'New Annotation', new_annotation_path %>

<table>
  <thead>
    <tr>
      <th>Next review date</th>
      <th>Category</th>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @annotations.each do |annotation| %>
      <tr>
        <td><%= annotation.next_review.date.strftime("%d/%m/%Y") %></td>
        <td><%= annotation.category.name %></td>
        <td><%= annotation.title %></td>
        <td><%= annotation.content %></td>
        <td><%= link_to 'Show', annotation %></td>
        <td><%= link_to 'Edit', edit_annotation_path(annotation) %></td>
        <td><%= link_to 'Destroy', annotation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/annotations/new.html.erb
<h1>New Annotation</h1>

<%= render 'form', annotation: @annotation %>

<%= link_to 'Back', annotations_path %>

app/views/annotations/show.html.haml
%p{:id => 'notice'}
  =notice

%p
  %strong Title
  =@annotation.title

%p
  %strong='Content'
  =@annotation.content

%p
  %strong='Category'
  =@annotation.category.name

%p
  %strong='Next review date'
  =@annotation.next_review.date.strftime("%d/%m/%Y")

=link_to 'Dashboard', dashboard_path
=link_to 'Edit', edit_annotation_path(@annotation)
=link_to 'Back', annotations_path